### ISSUE TITLE
Add image size hint

### ISSUE THREAD

**Issue by nyalldawson** [elpaso/qgis-feed#3]
Could we add a hint to users on the desired image size? In the frontend images are restricted to a maximum width of 250 pixels and maximum height of 177 pixels. This is to match the size of recent project and template preview images (not sure on the origin of these sizes!!). So I'd like to see a bit of helper text:

  "Ideal image size is 250px x 177. Larger images will be resized down"

**Comment by nyalldawson** [comment]
Actually - for bandwidth efficiency, we should block any images larger than this size. No point serving up 2000 x 2000 px images for the client to resize them down to 250px wide...

**Comment by elpaso** [comment]
Got it, we can resize and crop automatically.

**Comment by elpaso** [comment]
Shall we also pre-store -2x images for hidpi?

**Comment by nyalldawson** [comment]
The welcome page model doesn't adapt for hi dpi currently, but I've honestly not noticed an issue with this

**Comment by elpaso** [comment]
if we don't want blurry images we need to resize/crop for hidpi. Should I make them 500x354 instead of 250x177 ?

**Comment by nyalldawson** [comment]
What I mean is that on my hidpi laptop the images just show at half size, but it seems ok like that to me anyway :p but if it's trivial to do, go ahead!
